title: Till Straube

baseurl: "/~tstraube"
doc_path: "docs/"
url: "https://uni-frankfurt.de"
twitter: tillstr
scholar: KeAyNsgAAAAJ
github: ktiu

sass:
  style: compact

plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

collections:
  sections:
     order:
       - about.md
       - publications.md
       - teaching.md
       - contact.md

# i18n
languages: ["en", "de"]
exclude_from_localizations: ["docs", "assets", "css"]
  
keep_files: ["c", "box"]

exclude:
  - README.md
  - LICENSE
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
